### ISSUE TITLE
Licensing terms

### ISSUE THREAD

**Issue by jakobwilm** [ethz-asl/sl_sensor#10]
Hi Teng Foon and ETHZ team

It is good to see work in this field and I can see you do build on some of the ideas from SLStudio. 
Please make sure all licensing terms are honored. 

Sincerely
Jakob Wilm, Assoc. Prof., SDU Robotics

**Comment by tengfoonglam** [comment]
@jakobwilm 

We thank you for your work on SLStudio, which helped us tremendously in the development of SL Sensor.

To the best of our knowledge, we believe that we have taken the appropriate measures to conform to the licensing requirements of SLStudio. This includes citing your works in our publication, acknowledging SLStudio in our README, made our code open source and licensed SL Sensor under AGPL-3.0.
